defaults:
  - default.yaml

train:
  dataset:
    _target_: comprx.dataloaders.ConcatDataset
    dataset_ids:
      - ${dataset_id}
    datasets:
      # CANDID-PTX Chest X-Rays
      - _target_: comprx.dataloaders.GenericDataset
        split_path: ${paths.data_dir}/vae/cr-1/splits/train.csv
        data_dir: ${paths.data_dir}/vae/cr-1/data/${data_subdir}
        dataset_id: 7
        img_column: image_uuid
        img_suffix: .img.npy
        img_transform:
          _target_: torchvision.transforms.Compose
          transforms:
            - _partial_: true
              _target_: comprx.utils.loaders.load_tensor
            - _target_: torchvision.transforms.Normalize
              mean: [0.4850]
              std: [0.2290]
        lbl_columns: ["fracture"]
        lbl_transform:
          _partial_: true
          _target_: comprx.utils.loaders.load_labels
          dtype: float32
          squeeze: -1

valid:
  dataset:
    _target_: comprx.dataloaders.ConcatDataset
    dataset_ids:
      - ${dataset_id}
    datasets:
      # CANDID-PTX Chest X-Rays
      - _target_: comprx.dataloaders.GenericDataset
        split_path: ${paths.data_dir}/vae/cr-1/splits/valid.csv
        data_dir: ${paths.data_dir}/vae/cr-1/data/${data_subdir}
        dataset_id: 7
        img_column: image_uuid
        img_suffix: .img.npy
        img_transform:
          _target_: torchvision.transforms.Compose
          transforms:
            - _partial_: true
              _target_: comprx.utils.loaders.load_tensor
            - _target_: torchvision.transforms.Normalize
              mean: [0.4850]
              std: [0.2290]
        lbl_columns: ["fracture"]
        lbl_transform:
          _partial_: true
          _target_: comprx.utils.loaders.load_labels
          dtype: float32
          squeeze: -1
