defaults:
  - default.yaml

train:
  dataset:
    _target_: comprx.dataloaders.ConcatDataset
    datasets:
      # RSNA Mammography
      - _partial_: true
        _target_: comprx.dataloaders.MGDataset
        split_path: ${paths.data_dir}/mg/train.csv
        split_column: split
        split_name: train
        data_dir: ${paths.data_dir}/mg/train_images
        dataset_id: 1
        img_column: image_id
        img_suffix: .dcm
        img_transform:
          _target_: torchvision.transforms.Compose
          transforms:
            - _target_: torchvision.transforms.Resize
              size:
                - ${img_size}
                - ${img_size}
              interpolation: 3
              antialias: True
            - _target_: torchvision.transforms.Normalize
              mean: [0.5]
              std: [0.5]

valid:
  dataset:
    _target_: comprx.dataloaders.ConcatDataset
    datasets:
      # RSNA Mammography
      - _partial_: true
        _target_: comprx.dataloaders.MGDataset
        split_path: ${paths.data_dir}/mg/test.csv
        split_column: split
        split_name: test
        data_dir: ${paths.data_dir}/mg/test_images
        dataset_id: 1
        img_column: image_id
        img_suffix: .dcm
        img_transform:
          _target_: torchvision.transforms.Compose
          transforms:
            - _target_: torchvision.transforms.Resize
              size:
                - ${img_size}
                - ${img_size}
              interpolation: 3
              antialias: True
            - _target_: torchvision.transforms.Normalize
              mean: [0.5]
              std: [0.5]
